/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ideastarter.interfaces;

import com.sun.media.sound.ModelAbstractChannelMixer;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thaer
 */
public class GestionProjectAdminUpdate extends javax.swing.JFrame {

    /**
     * Creates new form GestionProjectAdminUpdate
     */
    DefaultTableModel model;
    public GestionProjectAdminUpdate() {
        initComponents();
        model=(DefaultTableModel) Tb_Projects.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tb_Projects = new javax.swing.JTable();
        Bt_add_back = new javax.swing.JButton();
        Bt_Add = new javax.swing.JButton();
        Lb_Add_category = new javax.swing.JLabel();
        StarDescription = new javax.swing.JTextField();
        StarInventor = new javax.swing.JTextField();
        Lb_add_commentary = new javax.swing.JLabel();
        Lb_Add_title = new javax.swing.JLabel();
        StarName = new javax.swing.JTextField();
        Bt_Delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tb_Projects = new javax.swing.JTable();
        Bt_Update = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        Tb_Projects.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Star Name", "Star Inventor", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tb_Projects.setOpaque(false);
        Tb_Projects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tb_ProjectsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tb_Projects);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 190, 350, 180);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(470, 530));
        getContentPane().setLayout(null);

        Bt_add_back.setText("Back");
        Bt_add_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_add_backActionPerformed(evt);
            }
        });
        getContentPane().add(Bt_add_back);
        Bt_add_back.setBounds(20, 450, 55, 23);

        Bt_Add.setText("add");
        Bt_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_AddActionPerformed(evt);
            }
        });
        getContentPane().add(Bt_Add);
        Bt_Add.setBounds(80, 390, 70, 23);

        Lb_Add_category.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lb_Add_category.setText("Star's inventor");
        getContentPane().add(Lb_Add_category);
        Lb_Add_category.setBounds(80, 90, 100, 17);

        StarDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StarDescriptionActionPerformed(evt);
            }
        });
        getContentPane().add(StarDescription);
        StarDescription.setBounds(180, 130, 150, 40);

        StarInventor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StarInventorActionPerformed(evt);
            }
        });
        getContentPane().add(StarInventor);
        StarInventor.setBounds(180, 90, 91, 30);

        Lb_add_commentary.setText("Description");
        getContentPane().add(Lb_add_commentary);
        Lb_add_commentary.setBounds(110, 130, 60, 14);

        Lb_Add_title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Lb_Add_title.setText("Star's Name");
        getContentPane().add(Lb_Add_title);
        Lb_Add_title.setBounds(40, 40, 130, 40);

        StarName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StarNameActionPerformed(evt);
            }
        });
        getContentPane().add(StarName);
        StarName.setBounds(180, 50, 91, 30);

        Bt_Delete.setText("Delete");
        Bt_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Bt_Delete);
        Bt_Delete.setBounds(270, 390, 80, 23);

        Tb_Projects.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Star Name", "Star Inventor", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tb_Projects.setOpaque(false);
        Tb_Projects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tb_ProjectsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tb_Projects);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 190, 350, 180);

        Bt_Update.setText("Update");
        Bt_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(Bt_Update);
        Bt_Update.setBounds(170, 390, 80, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ideastarter/Image/managementFond20.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 0, 460, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bt_add_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_add_backActionPerformed
        // TODO add your handling code here:

        this.dispose();

    }//GEN-LAST:event_Bt_add_backActionPerformed

    private void Bt_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_AddActionPerformed
        // TODO add your handling code here:
        model.insertRow(model.getRowCount(),new Object[]{StarName.getText(),StarInventor.getText(),StarDescription.getText()});
        JOptionPane.showMessageDialog(null, "file added with success ");
    }//GEN-LAST:event_Bt_AddActionPerformed

    private void StarDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StarDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StarDescriptionActionPerformed

    private void StarNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StarNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StarNameActionPerformed

    private void StarInventorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StarInventorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StarInventorActionPerformed

    private void Bt_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_UpdateActionPerformed
        // TODO add your handling code here:
        model.setValueAt(StarName.getText(), Tb_Projects.getSelectedRow(), 0);
        model.setValueAt(StarInventor.getText(), Tb_Projects.getSelectedRow(), 1);
        model.setValueAt(StarDescription.getText(), Tb_Projects.getSelectedRow(), 2);

    }//GEN-LAST:event_Bt_UpdateActionPerformed

    private void Tb_ProjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tb_ProjectsMouseClicked
        // TODO add your handling code here:

        StarName.setText(String.valueOf(model.getValueAt(Tb_Projects.getSelectedRow(), 0)));
        StarInventor.setText(String.valueOf(model.getValueAt(Tb_Projects.getSelectedRow(), 1)));
        StarDescription.setText(String.valueOf(model.getValueAt(Tb_Projects.getSelectedRow(), 2)));

    }//GEN-LAST:event_Tb_ProjectsMouseClicked

    private void Bt_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_DeleteActionPerformed
        // TODO add your handling code here:
        model.removeRow(Tb_Projects.getSelectedRow());

        JOptionPane.showMessageDialog(null, "The project has been deleted with success");
    }//GEN-LAST:event_Bt_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionProjectAdminUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionProjectAdminUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionProjectAdminUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionProjectAdminUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionProjectAdminUpdate().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_Add;
    private javax.swing.JButton Bt_Delete;
    private javax.swing.JButton Bt_Update;
    private javax.swing.JButton Bt_add_back;
    private javax.swing.JLabel Lb_Add_category;
    private javax.swing.JLabel Lb_Add_title;
    private javax.swing.JLabel Lb_add_commentary;
    private javax.swing.JTextField StarDescription;
    private javax.swing.JTextField StarInventor;
    private javax.swing.JTextField StarName;
    private javax.swing.JTable Tb_Projects;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
